import { Router } from "express"

import { CreditCard } from "../models/CreditCard.js"
import { CardMonthly } from "../models/CardMonthly.js"
import { cardCreateSchema, cardMonthSchema, cardPatchSchema, validate } from "../validation.js"
import { mapToObj } from "../utils.js"

const router = Router()

const CONFIG_FIELDS = [
  "name", "anniversaryStartMonth", "feeWaiverTarget", "status",
  "annualFeeType", "annualFeeAmount", "creditLimit", "benefitsNote",
]

function configToClient(doc) {
  const out = { id: doc.cardId }
  for (const f of CONFIG_FIELDS) out[f] = doc[f]
  return out
}

// GET assembles { creditCards, creditCardDataByYear } from both collections.
router.get("/", async (req, res) => {
  const [configs, monthly] = await Promise.all([
    CreditCard.find({ userId: req.userId }),
    CardMonthly.find({ userId: req.userId }),
  ])

  const creditCards = configs.map(configToClient)

  const creditCardDataByYear = {}
  for (const m of monthly) {
    if (!creditCardDataByYear[m.year]) creditCardDataByYear[m.year] = {}
    creditCardDataByYear[m.year][m.cardId] = {
      cashback: mapToObj(m.cashback),
      expenses: mapToObj(m.expenses),
    }
  }

  res.json({ creditCards, creditCardDataByYear })
})

// POST adds one card. The id is generated by the client. Safe to repeat (the
// client retries after a lost response): an existing card is left as it is.
router.post("/", validate(cardCreateSchema), async (req, res) => {
  const { id, ...config } = req.body
  const doc = await CreditCard.findOneAndUpdate(
    { userId: req.userId, cardId: id },
    { $setOnInsert: { ...config, userId: req.userId, cardId: id } },
    { new: true, upsert: true, setDefaultsOnInsert: true },
  )
  res.status(201).json(configToClient(doc))
})

// PATCH changes only the posted settings of one card.
router.patch("/:cardId", validate(cardPatchSchema), async (req, res) => {
  const doc = await CreditCard.findOneAndUpdate(
    { userId: req.userId, cardId: req.params.cardId },
    { $set: req.body },
    { new: true },
  )
  if (!doc) return res.status(404).json({ error: "Card not found" })
  res.json(configToClient(doc))
})

// DELETE removes one card and all of its monthly numbers. Safe to repeat:
// deleting a card that's already gone succeeds.
router.delete("/:cardId", async (req, res) => {
  const filter = { userId: req.userId, cardId: req.params.cardId }
  await CreditCard.deleteOne(filter)
  await CardMonthly.deleteMany(filter)
  res.json({ ok: true })
})

// PUT sets one month's cashback or spend for one card, e.g. `expenses.3`.
// Writes first and checks the card after: if the card is gone (or is deleted
// at the same moment), the row is removed again, so no orphan is left behind.
router.put("/:cardId/months", validate(cardMonthSchema), async (req, res) => {
  const { year, month, field, value } = req.body
  const filter = { userId: req.userId, cardId: req.params.cardId }
  await CardMonthly.updateOne(
    { ...filter, year },
    { $set: { [`${field}.${month}`]: value } },
    { upsert: true },
  )
  if (!(await CreditCard.exists(filter))) {
    await CardMonthly.deleteMany(filter)
    return res.status(404).json({ error: "Card not found" })
  }
  res.json({ ok: true })
})

export default router
